# NOME DO NOSSO PROJETO
spring.application.name=projeto-spring-boot-com-mysql

# URL DE CONEXÃO COM O BANCO
spring.datasource.url=jdbc:mysql://192.168.205.100:3306/ian_g_db

#CREDENCIAIS DO BANCO
spring.datasource.username=ian_g
spring.datasource.password=00219601

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update